version: '3'
services:
  nginx_proxy:
    container_name: nginx_proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert/petclinic.pem:/etc/nginx/cert/petclinic.pem
      - ./nginx/cert/petclinic.key:/etc/nginx/cert/petclinic.key
      - ./nginx/cert/petclinic.crt:/etc/nginx/cert/petclinic.crt
    depends_on:
      - petclinic
    links:
      - petclinic

  petclinic:
    container_name: petclinic  
    image: multi_pet:latest
#    build: .
    environment:
      - MYSQL_ROOT_PASSWORD=pet
#      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
      - MYSQL_URL=jdbc:mysql://mysql/petclinic
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=pet
 #     - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
